[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
auto_detect_remappings = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
quote_style = "double"
int_types = "long"
multiline_func_header = "params_first"
